- name: install and run nginx
  hosts: web
  connection: local
  become: yes
  tasks:
  - name: install nginx
    ansible.buildin.package:
      name: nginx
      state: present
  - name: start the nginx
    ansible.buildin.service:
      name: nginx
      state: started
      enabled: yes