- name: variables from files
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: name of the course
    private: flase
  - name: DURATION
    prompt: please enter duration
    private: flase
  - name: TRAINER
    prompt: name of the trainer
    private: flase
  tasks:
  - name: enter the course information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
